import { useEffect, useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';

import type { Challenge } from '@/challenges/ChallengeTypes';
import { Field, PrimaryButton, palette } from './GameUi';

export function ChallengeCard({ challenge, active, durationMs, startedAt, onSubmit }: { challenge: Challenge; active: boolean; durationMs: number; startedAt: number | null; onSubmit(value: string): void }) {
  const [answer, setAnswer] = useState(''); const [taps, setTaps] = useState(0); const [now, setNow] = useState(Date.now()); const [memoryVisible, setMemoryVisible] = useState(challenge.type === 'MEMORY'); const [submitted, setSubmitted] = useState(false);
  useEffect(() => { setAnswer(''); setTaps(0); setSubmitted(false); setMemoryVisible(challenge.type === 'MEMORY'); if (challenge.type !== 'MEMORY') return; const reveal = typeof challenge.metadata?.revealMs === 'number' ? challenge.metadata.revealMs : 1600; const timer = setTimeout(() => setMemoryVisible(false), reveal); return () => clearTimeout(timer); }, [challenge.id, challenge.metadata?.revealMs, challenge.type]);
  useEffect(() => { if (!active || !startedAt) return; const interval = setInterval(() => setNow(Date.now()), 200); return () => clearInterval(interval); }, [active, startedAt]);
  const seconds = useMemo(() => Math.max(0, Math.ceil((durationMs - (now - (startedAt ?? now))) / 1000)), [durationMs, now, startedAt]);
  const needsChoice = ['VISUAL', 'REACTION', 'ODD_ONE_OUT', 'TRUE_FALSE'].includes(challenge.type);
  const speedTarget = typeof challenge.metadata?.targetTaps === 'number' ? challenge.metadata.targetTaps : 5;
  const memoryItems = Array.isArray(challenge.metadata?.memoryItems) ? challenge.metadata.memoryItems : [];
  const locked = !active || submitted;
  const submit = (value: string) => { if (locked || !value.trim()) return; setSubmitted(true); onSubmit(value); };
  return <View style={styles.card}><View style={styles.row}><Text style={styles.eyebrow}>🧠 CHALLENGE</Text><Text style={[styles.timer, seconds <= 2 && styles.timerHot]}>{seconds}s</Text></View>{challenge.type === 'MEMORY' && memoryVisible ? <View style={styles.memory}><Text style={styles.memoryItems}>{memoryItems.join('  ')}</Text><Text style={styles.memoryHint}>MEMORIZE!</Text></View> : <><Text style={styles.prompt}>{challenge.prompt}</Text>{needsChoice ? <View style={styles.options}>{challenge.options?.map((option, index) => <Pressable key={`${option}-${index}`} accessibilityRole="button" disabled={locked} onPress={() => submit(challenge.type === 'VISUAL' || challenge.type === 'ODD_ONE_OUT' ? String(index + 1) : option)} style={({ pressed }) => [styles.option, pressed && styles.pressed, locked && styles.locked]}><Text style={challenge.type === 'VISUAL' || challenge.type === 'ODD_ONE_OUT' ? styles.emojiOption : styles.optionText}>{challenge.type === 'REACTION' ? option.toUpperCase() : option}</Text></Pressable>)}</View> : challenge.type === 'SPEED_TAP' ? <View style={styles.tapArea}><Text style={styles.tapCount}>{taps}/{speedTarget}</Text><Pressable accessibilityRole="button" disabled={locked} onPress={() => { const next = taps + 1; setTaps(next); if (next === speedTarget) submit(String(speedTarget)); }} style={({ pressed }) => [styles.tapButton, pressed && styles.pressed, locked && styles.locked]}><Text style={styles.tapText}>{submitted ? 'CHECKING…' : 'TAP!'}</Text></Pressable></View> : <><Field value={answer} onChangeText={setAnswer} editable={!locked} onSubmitEditing={() => submit(answer)} placeholder="TYPE YOUR ANSWER" returnKeyType="done" /><PrimaryButton label={submitted ? 'CHECKING ANSWER…' : 'SUBMIT ANSWER'} onPress={() => submit(answer)} disabled={locked || answer.trim().length === 0} tone="green" /></>}</>}</View>;
}

const styles = StyleSheet.create({
  card: { backgroundColor: '#101A39', borderWidth: 1, borderColor: '#334A7C', borderRadius: 22, padding: 17, gap: 13 }, row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, eyebrow: { color: palette.yellow, fontWeight: '900', letterSpacing: 1.4, fontSize: 11 }, timer: { color: palette.mint, fontWeight: '900', fontSize: 19 }, timerHot: { color: palette.red }, prompt: { color: palette.ink, fontSize: 21, lineHeight: 27, fontWeight: '900', textAlign: 'center', paddingVertical: 4 }, options: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', gap: 10 }, option: { minWidth: 68, minHeight: 55, flexGrow: 1, paddingHorizontal: 12, borderRadius: 14, backgroundColor: '#203661', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#4B6599' }, optionText: { color: '#F8FBFF', fontWeight: '900', fontSize: 14 }, emojiOption: { fontSize: 32 }, pressed: { transform: [{ scale: .96 }], opacity: .78 }, locked: { opacity: .48 }, tapArea: { alignItems: 'center', gap: 10 }, tapCount: { color: palette.ink, fontSize: 24, fontWeight: '900' }, tapButton: { backgroundColor: palette.violet, borderBottomColor: '#3D20AE', borderBottomWidth: 4, borderRadius: 18, paddingVertical: 15, width: '100%', alignItems: 'center' }, tapText: { color: '#FFFFFF', fontWeight: '900', letterSpacing: 1, fontSize: 18 }, memory: { alignItems: 'center', paddingVertical: 22, gap: 9 }, memoryItems: { fontSize: 33 }, memoryHint: { color: palette.yellow, fontSize: 13, fontWeight: '900', letterSpacing: 2 },
});
