import { router } from 'expo-router';
import { useEffect } from 'react';
import { ActivityIndicator, BackHandler, StyleSheet, Text, View } from 'react-native';

import { BombView } from '@/components/game/BombView';
import { ChallengeCard } from '@/components/game/ChallengeCard';
import { Brand, PrimaryButton, Screen, SecondaryButton } from '@/components/game/GameUi';
import type { Player } from '@/network/GameProtocol';
import { useGameSession } from '@/game/GameSession';

function PlayerChip({ player, self, holding, streak }: { player: Player; self: boolean; holding: boolean; streak: number }) {
  return <View style={[styles.player, holding && styles.playerHolding]}><Text numberOfLines={1} style={styles.playerName}>{self ? 'YOU' : player.name}</Text><Text style={styles.playerMeta}>{holding ? '💣 BOMB' : streak > 1 ? `🔥 ${streak}× STREAK` : 'READY'}</Text></View>;
}

export default function GameRoute() {
  const session = useGameSession(); const snapshot = session.snapshot;
  useEffect(() => { const subscription = BackHandler.addEventListener('hardwareBackPress', () => true); return () => subscription.remove(); }, []);
  useEffect(() => { if (session.connection === 'DISCONNECTED' || session.connection === 'FAILED') { void session.cancel(); router.replace('/'); return; } if (snapshot?.phase === 'lobby') router.replace('/lobby'); }, [session.connection, snapshot]);
  if (!snapshot) return <Screen><ActivityIndicator color="#FFD31A" /></Screen>;
  const holding = snapshot.bombOwnerId === session.localPlayerId;
  const lost = snapshot.loserId === session.localPlayerId;
  const result = snapshot.phase === 'result'; const countdown = snapshot.phase === 'countdown';
  const challengeActive = snapshot.phase === 'challenge_active'; const waitingForAuthority = snapshot.phase === 'answer_submitted'; const passUnlocked = snapshot.phase === 'ready_to_pass';
  const panic = snapshot.difficulty === 'PANIC' || snapshot.difficulty === 'HARD';
  const title = countdown ? 'GET READY!' : result ? (lost ? 'YOU GOT BOOMED!' : 'YOU SURVIVED!') : holding ? passUnlocked ? 'PASS NOW!' : 'YOUR BOMB!' : 'RIVAL HAS IT';
  const subtitle = countdown ? snapshot.notice : result ? (lost ? 'You were holding the bomb.' : `${snapshot.players.find((player) => player.id === snapshot.loserId)?.name ?? 'Your rival'} got BOOMED!`) : holding ? passUnlocked ? 'Challenge cleared. Get it out of your hands!' : waitingForAuthority ? snapshot.notice : 'Solve fast — the bomb will not wait.' : 'A new challenge is waiting for your rival.';
  return <Screen><View style={styles.game}><Brand compact /><View style={styles.players}>{snapshot.players.map((player) => <PlayerChip key={player.id} player={player} self={player.id === session.localPlayerId} holding={player.id === snapshot.bombOwnerId && !result} streak={snapshot.playerStats[player.id]?.streak ?? 0} />)}</View><View style={styles.stage}><BombView active={!countdown && !result} panic={panic} exploded={result} />{countdown ? <Text style={styles.count}>{snapshot.notice}</Text> : null}<Text style={styles.difficulty}>{result ? 'ROUND COMPLETE' : `${snapshot.difficulty} PRESSURE`}</Text></View><View style={styles.copyBlock}><Text style={[styles.title, result && (lost ? styles.lose : styles.win)]}>{title}</Text><Text style={styles.copy}>{subtitle}</Text></View>{holding && snapshot.challenge && !passUnlocked && !result ? <ChallengeCard challenge={snapshot.challenge} active={challengeActive} durationMs={snapshot.challengeDurationMs} startedAt={snapshot.challengeStartedAt} onSubmit={(value) => void session.answer(value)} /> : null}{passUnlocked && holding && !result ? <View style={styles.correct}><Text style={styles.correctTitle}>✅ CORRECT!</Text><Text style={styles.correctCopy}>Your pass is unlocked. Don’t hesitate.</Text></View> : null}{!holding && !countdown && !result ? <View style={styles.waitCard}><Text style={styles.waitIcon}>👀</Text><Text style={styles.waitText}>KEEP WATCH</Text><Text style={styles.waitCopy}>Your rival must clear their challenge before they can pass the bomb.</Text></View> : null}<View style={styles.actions}>{!result && !countdown ? <PrimaryButton label={passUnlocked && holding ? 'PASS THE BOMB 💣' : holding ? (waitingForAuthority ? 'CHECKING ANSWER…' : 'PASS LOCKED') : 'WAIT FOR IT…'} onPress={() => void session.pass()} disabled={!holding || !passUnlocked} tone={passUnlocked && holding ? 'orange' : 'violet'} /> : null}{result ? <><PrimaryButton label={snapshot.rematchPlayerIds.includes(session.localPlayerId) ? 'REMATCH REQUESTED' : 'REMATCH'} onPress={() => void session.rematch()} disabled={snapshot.rematchPlayerIds.includes(session.localPlayerId)} /><SecondaryButton label="⌂  MAIN MENU" onPress={() => { void session.cancel(); router.replace('/'); }} /></> : <SecondaryButton label="LEAVE GAME" onPress={() => { void session.cancel(); router.replace('/'); }} />}</View></View></Screen>;
}

const styles = StyleSheet.create({
  game: { gap: 14 }, players: { flexDirection: 'row', gap: 9 }, player: { flex: 1, minWidth: 0, borderRadius: 15, backgroundColor: '#111B3C', padding: 11, borderWidth: 1, borderColor: '#2C4270', gap: 3 }, playerHolding: { backgroundColor: '#4B2034', borderColor: '#FF5867' }, playerName: { color: '#F8FBFF', fontSize: 13, fontWeight: '900' }, playerMeta: { color: '#A9B7D8', fontSize: 10, fontWeight: '900', letterSpacing: .5 }, stage: { minHeight: 224, borderRadius: 29, backgroundColor: '#0D1632', borderWidth: 1, borderColor: '#273D70', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' }, count: { position: 'absolute', color: '#FFD31A', fontSize: 132, fontWeight: '900', textShadowColor: '#FF7100', textShadowRadius: 16 }, difficulty: { position: 'absolute', bottom: 14, color: '#A9B7D8', fontWeight: '900', fontSize: 10, letterSpacing: 1.6 }, copyBlock: { alignItems: 'center', gap: 5 }, title: { color: '#F8FBFF', fontSize: 29, lineHeight: 35, fontWeight: '900', letterSpacing: -.8, textAlign: 'center' }, lose: { color: '#FF6270' }, win: { color: '#27D98B' }, copy: { color: '#A9B7D8', fontSize: 14, lineHeight: 20, textAlign: 'center', paddingHorizontal: 9 }, correct: { padding: 17, alignItems: 'center', borderRadius: 20, backgroundColor: '#103E36', borderWidth: 1, borderColor: '#2AD999', gap: 4 }, correctTitle: { color: '#5CF0B2', fontSize: 22, fontWeight: '900' }, correctCopy: { color: '#C5F7E2', fontSize: 13, fontWeight: '700', textAlign: 'center' }, waitCard: { minHeight: 122, padding: 16, borderRadius: 20, backgroundColor: '#111B3C', borderWidth: 1, borderColor: '#2C4270', alignItems: 'center', justifyContent: 'center', gap: 4 }, waitIcon: { fontSize: 29 }, waitText: { color: '#F8FBFF', fontSize: 13, letterSpacing: 1.7, fontWeight: '900' }, waitCopy: { color: '#A9B7D8', textAlign: 'center', fontSize: 13, lineHeight: 18 }, actions: { gap: 10, marginTop: 2, marginBottom: 8 },
});
