import { router } from 'expo-router';
import { useEffect } from 'react';
import { ActivityIndicator, StyleSheet, Text, View } from 'react-native';

import { BombMascot, Brand, ConnectionStatus, Header, PrimaryButton, Screen, SecondaryButton } from '@/components/game/GameUi';
import { useGameSession } from '@/game/GameSession';

export default function LobbyRoute() { const session = useGameSession(); const snapshot = session.snapshot; useEffect(() => { if (session.connection === 'DISCONNECTED' || session.connection === 'FAILED') { void session.cancel(); router.replace('/'); return; } if (snapshot && snapshot.phase !== 'lobby') router.replace('/game'); }, [session.connection, snapshot]); if (!snapshot) return <Screen><ActivityIndicator color="#FFD31A" /></Screen>; const local = snapshot.players.find((p) => p.id === session.localPlayerId) ?? snapshot.players[0]!; const rival = snapshot.players.find((p) => p.id !== local.id); const bothReady = !!rival && local.ready && rival.ready; const canToggleReady = !!rival && session.connection === 'CONNECTED'; return <Screen><Brand compact /><Header eyebrow="CONNECTED DUEL" title="Ready for the panic?" /><BombMascot size={140} style={styles.mascot} /><Player player={local} self /><Text style={styles.vs}>VS</Text>{rival ? <Player player={rival} /> : <View style={styles.wait}><ActivityIndicator color="#FFD31A" /><Text style={styles.waitText}>Waiting for your rival to arrive…</Text></View>}<ConnectionStatus state={session.connection} detail={snapshot.notice} /><PrimaryButton label={!rival ? 'WAITING FOR RIVAL' : local.ready ? 'NOT READY' : 'I’M READY'} onPress={() => void session.ready()} disabled={!canToggleReady} tone="green" />{session.role === 'host' && <PrimaryButton label={bothReady ? 'START THE ROUND' : 'WAITING FOR BOTH READY'} onPress={() => void session.start()} disabled={!bothReady} tone="orange" />}<Text style={styles.note}>Both players need to be ready. Only the host can start the round.</Text><SecondaryButton label="LEAVE GAME" onPress={() => { void session.cancel(); router.replace('/'); }} /></Screen>; }
function Player({ player, self = false }: { player: { name: string; ready: boolean }; self?: boolean }) { return <View style={[styles.player, self && styles.self]}><Text style={styles.name}>{player.name}{self ? ' (You)' : ''}</Text><Text style={player.ready ? styles.ready : styles.connected}>{player.ready ? 'READY ✓' : 'CONNECTED'}</Text></View>; }
const styles = StyleSheet.create({ mascot: { alignSelf: 'center', marginTop: -32, marginBottom: -24 }, player: { borderWidth: 1, borderColor: '#2C3F70', borderRadius: 18, padding: 18, backgroundColor: '#101A39', flexDirection: 'row', justifyContent: 'space-between' }, self: { borderColor: '#FFD31A' }, name: { color: '#F8FBFF', fontSize: 18, fontWeight: '800' }, ready: { color: '#27D98B', fontSize: 12, fontWeight: '900' }, connected: { color: '#A9B7D8', fontSize: 12, fontWeight: '800' }, vs: { color: '#FFD31A', fontWeight: '900', textAlign: 'center', fontSize: 12, letterSpacing: 2 }, wait: { alignItems: 'center', gap: 10, padding: 20, borderWidth: 1, borderStyle: 'dashed', borderColor: '#354A80', borderRadius: 18 }, waitText: { color: '#A9B7D8' }, note: { color: '#8090B6', fontSize: 12, textAlign: 'center' } });
